/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package scientific;

public class App {

    public static void main(String[] args) {
        Pi pi = new Pi();
        System.out.println(pi.getValue());
    }
}
